/** Configurable parameters for the order-flow monitor. */
export const PRE_MOVE_WINDOWS = [5, 10, 30, 60, 300, 900];

export const PRE_MOVE_WEIGHTS = {
  up: {
    BuyAggressionPower: 0.25,
    BuyExecutionVelocity: 0.1,
    BuyImbalanceStrength: 0.1,
    AskCancellation: 0.12,
    AskWithdrawal: 0.12,
    AskConsumption: 0.1,
    AskDepthThinness: 0.08,
    AskDefenseWeakening: 0.08,
    AskReplenishment: -0.08,
    AskSurvival: -0.05,
    PassiveSellerDefense: -0.02,
  },
  down: {
    SellAggressionPower: 0.25,
    SellExecutionVelocity: 0.1,
    SellImbalanceStrength: 0.1,
    BidCancellation: 0.12,
    BidWithdrawal: 0.12,
    BidConsumption: 0.1,
    BidDepthThinness: 0.08,
    BidDefenseWeakening: 0.08,
    BidReplenishment: -0.08,
    BidSurvival: -0.05,
    PassiveBuyerDefense: -0.02,
  },
  attack: {
    aggression: 0.4,
    velocity: 0.2,
    imbalance: 0.2,
    large: 0.2,
  },
  bookPrep: {
    depthThinness: 0.18,
    cancellation: 0.18,
    withdrawal: 0.18,
    survivalFall: 0.14,
    approachWithdrawal: 0.14,
    nearTouchFall: 0.12,
    replenishWeak: 0.06,
  },
  defenseWeaken: {
    survivalFall: 0.22,
    depthFall: 0.16,
    cancellation: 0.16,
    replenishFall: 0.16,
    wallApproach: 0.16,
    consumedUnreplaced: 0.14,
  },
};

export const CONFIG = {
  symbol: "btcusdt",
  windows: [60, 300, 900, 1800, 2700],
  preMove: {
    windows: PRE_MOVE_WINDOWS,
    primaryWindow: 10,
    velocityWindows: [5, 10, 30, 60, 300],
    nearTouchLevels: 3,
    depthLevels: 20,
    largeTradeQuantile: 0.8,
    historyMaxPoints: 4200,
    weights: PRE_MOVE_WEIGHTS,
    hysteresis: {
      strongEnter: 80,
      strongExit: 65,
      buildingEnter: 58,
      buildingExit: 48,
      minPersistenceMs: 1500,
      cooldownMs: 800,
      transientMaxSec: 4,
    },
    persistence: {
      elevatedThreshold: 70,
      buildingSec: 8,
      persistentSec: 20,
      veryPersistentSec: 45,
    },
    forwardHorizons: [1, 5, 10, 30, 60, 300],
  },
  bookDepthLimit: 1000,
  nearBookLevels: 20,
  footprintBidLevels: 30,
  footprintAskLevels: 30,
  footprintDepthLimit: 100, // REST ladder for deeper footprint rows
  footprintDepthRefreshMs: 2000,
  wallPercentile: 95,
  wallMultiplier: 3.0,
  bookMode: "partial20", // partial20 (reliable) | full (REST+diff when ID spaces match)
  minimumWallLifetimeMs: 500,
  minimumCancelVolume: 0.05,
  minimumStackVolume: 0.05,
  cancelSurgeRatio: 0.5,
  minimumRefillRatio: 0.3,
  sweepExecutionRatio: 0.7,
  pullCancelRatio: 0.7,
  sweepDepletionRatio: 0.7,
  priceResponseTicks: 2,
  signalPersistenceMs: 1000,
  tradeBookMatchToleranceMs: 250,
  epsilon: 1e-9,
  dashboardRefreshHz: 4,
  footprintIntervalSec: 5,
  footprintColumns: 48,
  footprintPricePrecision: 1,
  restBase: "https://fapi.binance.com",
  // Primary futures WS; some networks block fstream.binance.com TLS.
  wsBase: "wss://fstream.binancefuture.com",
  wsFallbacks: [
    "wss://fstream.binancefuture.com",
    "wss://fstream.binance.com",
  ],
};
